### PR TITLE
issues-107 Wildchests and networks bug glitch (compatibility)

### PR DESCRIPTION
**Pull request by RelativoBR**
compatibility fix, to ignore WillChests API chests generating duplicate items

### CODE REVIEW

**Comment by RelativoBR** [comment]
Error encountered when there is no such plugin (WillChests) on the server.

Slimefun Data:
  ID: NTW_VANILLA_GRABBER
  Inventory: true
  Data: {"id":"NTW_VANILLA_GRABBER","uuid":"abfa5078-943d-4c24-b67f-b04d5406d673","direction":"NORTH"}

Stacktrace:

java.lang.NoClassDefFoundError: com/bgsoftware/wildchests/api/WildChestsAPI
	at networks vMODIFIED_1.1.0.jar//io.github.sefiraat.networks.slimefun.network.NetworkVanillaGrabber.tryGrabItem(NetworkVanillaGrabber.java:112)
	at networks vMODIFIED_1.1.0.jar//io.github.sefiraat.networks.slimefun.network.NetworkVanillaGrabber.onTick(NetworkVanillaGrabber.java:61)
	at networks vMODIFIED_1.1.0.jar//io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:99)
	at Slimefun4 - DEV 1035 (git 0b7c6).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:182)
	at Slimefun4 - DEV 1035 (git 0b7c6).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:163)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1492)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1416)
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.bgsoftware.wildchests.api.WildChestsAPI
	... 13 more

**Comment by RelativoBR** [comment]
Working on the fix, with the plugin it works, just need to add a plugin check.

**Comment by RelativoBR** [comment]
[add WildChests in SupportedPluginManager](https://github.com/Sefiraat/Networks/pull/122/commits/c2ae2b900d92cb643f06b51e8370a49a4187e26a)

The change passed all my tests.

**Comment by Sefiraat** [comment]
Thanks for the PR, I'll keep an eye on it. Would ideally like to test it myself as well given the scope here. You're a star!

**Comment by SrMonsterYT** [comment]
I forgot to mention that I was with the relative when the addon was tested, and the bug was fixed

**Comment by Sefiraat** [comment]
Compatibility was added, not fixing a bug :) 

I'll test and ship asap.

**Comment by SrMonsterYT** [comment]
sorry to bother you but the bug was resolved and added compatibility, I tested it myself along with it, what happens is that there is no longer how to put wildcard items on the networks and this has solved the bug, and would very much like this to be approved so I can return with the items of the networks on my server

**Review by Sefiraat — APPROVED** [review]

**Pull request merged**
