### PR TITLE
Feature/shells rewrite

### PR DESCRIPTION
**Pull request by Sefiraat**
Rewrite shells into a more boring item but without the issues for larger servers.

### CODE REVIEW

**Comment by Jelcoo** [comment]
[Suggestion] When you place a sign on a quantum block, display the item and the amount of the item on the sign (Like InfinityExpantion)

**Comment by Sefiraat** [comment]
> [Suggestion] When you place a sign on a quantum block, display the item and the amount of the item on the sign (Like InfinityExpantion)

I cant do that without entering the main thread and also I want to ensure I am not competing with InfinityExpansion or Fluffy. The Quantum Storages here are cheaper than IE but are designed to be less user-friendly without a network attached. This was I am not trying to out-do a very well made block with a very well designed purpose :)

**Comment by Jelcoo** [comment]
Please do remove the automatic void setting

**Comment by Sefiraat** [comment]
Void true will be the default as it's the least intensive on the server and is therefore it becomes an active choice that a player is not voiding and then scanning the whole network each tick. I wasn't a big fan of adding a toggle but I will 100% keep pushing voiding as a default and best practice.

**Pull request merged**
