### PR TITLE
Fix dupe #192 #188 #201

### PR DESCRIPTION
**Pull request by magiauy**

### CODE REVIEW

**Comment by dio2282** [comment]
Work Perfectly on my server

**Comment by balugaq** [comment]
Cannot reproduce #188 #192 #201 again ;)

**Review by dio2282 — APPROVED** [review]
Worked Perfectly

**Review by lijinhong11 — APPROVED** [review]

**Review by balugaq — APPROVED** [review]

**Comment by lijinhong11** [comment]
草泥马Sefi

**Comment by lijinhong11** [comment]
There's a fixed version: <https://www.mediafire.com/file/al99589iui2m2el/networks_vMODIFIED.jar/file>

**Pull request closed without merging**
